### PR TITLE
Fixes - implementing group access controls. dams5-cc-pilot#44

### PR DESCRIPTION
**Pull request by lsitu**
https://github.com/ucsdlib/dams5-cc-pilot/issues/44

### CODE REVIEW

**Comment by lsitu** [comment]
@ucsdlib/developers Please review, comments ... etc.

**Comment by VivianChu** [comment]
👍

**Comment by hweng** [comment]
@lsitu It looks fine to me, except that I see there are several classes copied over from curation_concerns to our local app with only one line added, for example:
app/search_builders/curation_concerns/embargo_search_builder.rb
app/search_builders/curation_concerns/file_set_search_builder.rb
app/search_builders/curation_concerns/lease_search_builder.rb
.....

Would it cause some future issues like Upgrading the curation_concerns gem causing the local app broken?  Is there better way.  Otherwise :+1:

**Comment by lsitu** [comment]
@hweng Yes, it could be but it should be an easy fix as well since the change is wrapped up in one line. With the merging of CC/Sufia is on going, I would expect some big changes in the future.

**Comment by lsitu** [comment]
@ucsdlib/developers Could anyone convenient to merge it for now? We may want other features to build on top of this group access controls. Thanks.

**Comment by lsitu** [comment]
@ucsdlib/developers Thank you all for the reviewing and merging it. Yes, we could look forward to the new CC/Sufia and see what's the better way for it. But now, I am just trying to make it easy for us to track and update later.

**Pull request merged**
