### PR TITLE
Fixes #14 migrate ansible playbook from cc-pilot repo

### LINKED ISSUE #14: Port Ansible playbook from CC pilot repo
It looks like we still need to port the ansible work @jhriv did into this repository.

### PR DESCRIPTION
**Pull request by mcritchlow**
This PR:
* Migrates the playbook and config that @jhriv setup in the CC-pilot repo
* Renames CC things to Hyrax in anticipation of #15 
* Renames primary group to `horton` to match repo name convention used in cc-pilot repo

### CODE REVIEW

**Comment by lsitu** [comment]
@jhriv When running `cd playbooks; vagrant up`, I got error "ERROR! The vault password file /Users/lsitu/Documents/git/horton/playbooks/.vaultpassword was not found". Is file .vaultpassword required? I see it in .gitignore file. Should we address it in README.md if we can't put a default .vaultpassword file for vagrant?

**Comment by jhriv** [comment]
Currently, nothing is requiring a vault password so a simple "touch .vaultpassword" is sufficient. When we start to include things like database passwords then those will be encrypted with the key located in .vaultpassword which is why it has to stay out of the git repository.

**Comment by mcritchlow** [comment]
Ok, for now I'll add a note to the README on the vault password. Nice catch @lsitu

**Comment by lsitu** [comment]
@jhriv Now I got another error when running `cd playbooks; touch .vaultpassword; vagrant up`:
TASK [ucsdlib.ffmpeg : Make Secure, Temporary Directory] ***********************
fatal: [default]: FAILED! => {"changed": true, "cmd": ["mktemp", "-d", "/var/folders/g9/rfnzlq8x3lxfpvxd1lx8cp1jx71tqy/T//ansible.XXXXXX"], "delta": "0:00:00.003002", "end": "2017-01-06 19:45:12.563650", "failed": true, "rc": 1, "start": "2017-01-06 19:45:12.560648", "stderr": "mktemp: failed to create directory via template ‘/var/folders/g9/rfnzlq8x3lxfpvxd1lx8cp1jx71tqy/T//ansible.XXXXXX’: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @./playbook.retry

PLAY RECAP *********************************************************************
default                    : ok=11   changed=8    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by jhriv** [comment]
Oh I know what is happening there. Your local TMPDIR is being used on the remote side. I thought I fixed all those in the roles. I'll fix the ffmpeg role, and make sure the rest are clear of TMPDIR references.

**Comment by mcritchlow** [comment]
@lsitu ran into the same on my end. 

I've updated the series of steps to remove the `ansible-playbook` line, as @jhriv noted that the [vagrant provisioning](https://github.com/ucsdlib/horton/pull/19/files#diff-e5b69f716ee248b024ef0110830dc05fR8) executes the playbook.

**Comment by lsitu** [comment]
@mcritchlow Line 3. `ansible-playbook playbook.yml -K -k` doesn't work for our local environment, so I think we can only play it with vagrant `cd playbooks; touch .vaultpassword; vagrant up`. So we need to update the command for the vagrant VM as well. 
Is it correct, @jhriv ?

**Comment by mcritchlow** [comment]
@lsitu yep, i removed that line in the last commit https://github.com/ucsdlib/horton/pull/19/commits/46844f4eb208a8f4b2d993b0b2bfb95eb949197f leaving the `vagrant up` command that will run the playbook. Is that what you mean? Or if there another piece I missed? Thanks.

**Comment by lsitu** [comment]
@mcritchlow I am not sure whether we can run the Vagrant box directly without step 1-3 or not:`cd playbooks; vagrant up`. 
Should it be `cd playbooks; touch .vaultpassword; vagrant up`, or we still need step 1-3 before we can run `vagrant up`? Then `cd playbooks` in the Vagrant command is confusing in this case.

**Comment by mcritchlow** [comment]
@lsitu - Ah, gotcha. Yes, I agree that's not clear in the README as-is. I suspect we want to remove the top section (Steps 1-3) and add in the vaultpassword touch to the Vagrant section. That sound right, at least for now, @jhriv ?

**Comment by jhriv** [comment]
I've updated the solr and fame roles. Please clear them out `rm -rf roles/ucsdlib.ffmpeg roles/ucsdlib.solr` and re-run the `setup.sh` or you can force install all the roles `ansible-galaxy install --role-file=config/roles.yml --roles-path=roles --force`

**Comment by mcritchlow** [comment]
@jhriv - yep that worked, and per our conversation I've commented out the vaultpassword from the ansible config file, so that step is no longer necessary. 

If this looks good to you and @lsitu can one of you do Review/Merge thing?

**Comment by mcritchlow** [comment]
@jhriv is going to submit a separate PR that changes a number of things that overlap (and are in addition to) this migration of the previous playbook, roles, and config. Therefore, we'll close this PR in anticipation of that.

**Pull request closed without merging**
