### PR TITLE
Fixes migrating to Hyrax with Rails 5.0.1. #15

### PR DESCRIPTION
**Pull request by lsitu**
Related: https://github.com/ucsdlib/horton/issues/15
Issues found: Hyrax "out of the box" can only ingest one file with batch ingest while several are files selected locally, and no files will be ingested with remote files selected from server side storage. CSV ingest support have the similar problem, which is derived from the underlying batch ingest issue in Hyrax.

### CODE REVIEW

**Comment by mcritchlow** [comment]
@lsitu - Thanks for all this hard work  👏 

After a bit of testing locally, my hunch is the default/fallback active job solution (`:async`) is our culprit for the local file issue. Perhaps in Rails 4 the default solution or behavior changed. I'm honestly not sure. 

How I was able to fix this, was to switch to using a "real" queue system. Since the [community is largely using sidekiq](http://blog.scoutapp.com/articles/2017/01/09/state-of-the-2017-rails-stack) now, for both performance and ease of setup reasons, I used that and suspect we'll want to as well. If you get a chance, I'd be curious if this solves the local file batch upload issue for you. Here are the steps I took to get Sidekiq working:

1. Add `sidekiq` gem to `Gemfile` and `bundle install`
2. Create a `config/sidekiq.yml` file and name the queues. This was an issue I ran into, since by default Sidekiq looks to process things that hit the `default` queue, while the Hyrax code uses differently named queues.
```
---
:queues:
  - default
  - event
  - attach_files
  - characterize
  - ingest
  - derivatives
  - batch_create
  - proxy_deposit
  - create_work
  - audit
  - import_url
  - ingest_local
  - resolrize
  - permissions
```
3. In `config/application.rb` inside the Application class, set sidekiq as the queue system
`config.active_job.queue_adapter = :sidekiq`

4. Add the sidekiq web interface routes in `config/routes.rb` (obviously we'll have to lock this down in the future). This way you can monitor things getting enqueued, completed, errors, etc:
```
require 'sidekiq/web
mount Sidekiq::Web => '/sidekiq'
```

5. Make sure in addition to starting `redis-server` and the `rake:hydra-server` services in separate tabs/windows, you also start sidekiq in a separate tab/window with:
`bundle exec sidekiq`

**Comment by lsitu** [comment]
That's promising and I'll try it later. Thanks @mcritchlow .

**Comment by lsitu** [comment]
@mcritchlow I've tried to use sidekiq and it looks good. But I see lots of warnings and the ingest will be delayed for a while for records/thumbnails to be showing up:
WARN: ActiveJob::DeserializationError: Error while trying to deserialize arguments:
WARN: /Users/lsitu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ldp-0.6.2/lib/ldp/client/methods.rb:119:in `block in check_for_errors'
/Users/lsitu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ldp-0.6.2/lib/ldp/client/methods.rb:117:in `tap'
/Users/lsitu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ldp-0.6.2/lib/ldp/client/methods.rb:117:in `check_for_errors'
/Users/lsitu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ldp-0.6.2/lib/ldp/client/methods.rb:25:in `block in head'
/Users/lsitu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
...

It looks like the queue configuration used by Plum in Princeton  works a little bit better with less warnings:
:queues:
  - high
  - ingest
  - default

**Comment by mcritchlow** [comment]
@lsitu given the last comment exchange in #17 (https://github.com/ucsdlib/horton/issues/17#issuecomment-273224147) what are your thoughts on moving this ticket ahead? Have the rest of @ucsdlib/developers review knowing that more queue work will be done in that separate ticket? Or are there more issues to sort through first?

**Comment by lsitu** [comment]
@mcritchlow I think we can separate the queue issue and proceeded with the review for this ticket. And yes, having the rest of @ucsdlib/developers review knowing that more queue work will be done in that separate ticket. Would you like to add a commit for using the Sidekid queue here, or leave it for ticket https://github.com/ucsdlib/horton/issues/17 as the next step?

**Comment by mcritchlow** [comment]
@lsitu - good question. Do the tests (in as much as we have them) pass for you locally? Part of why I'm asking is that if they do, it would give @VivianChu a new base for #13 which we need to get working asap.

**Comment by lsitu** [comment]
@mcritchlow Yes, the tests are passed locally and it looks good except that CSV Import/Batch Ingest issue that I noted above.

**Comment by VivianChu** [comment]
@lsitu - I tried to run the tests for this branch feature/hyrax_migration and I got 88 failures.  Do you know if I need to install anything to make them pass locally?  Thanks

**Comment by lsitu** [comment]
@VivianChu I don't think we need to install anything. I just did `gem install rails -v 5.0.0.1` at the very beginning which might not be necessary. But please stop all the servers, then run `bundle install` and restart them to see whether it make any difference.

**Comment by VivianChu** [comment]
@lsitu - I still got 88 errors after gem install rails -v 5.0.0.1 at the very beginning.

**Comment by lsitu** [comment]
@VivianChu Could you post some of the errors you got?

**Comment by VivianChu** [comment]
@lsitu - 87) ObjectResource Object Resource should has topic
      Failure/Error: phd_obj.save ({:validate => false})
      
      ActiveRecord::StatementInvalid:
        Could not find table 'minter_states'
      # ./spec/models/object_resource_spec.rb:63:in `block (3 levels) in <top (required)>'

  88) ObjectResource Object Resource should has language url
      Failure/Error: lan_obj.save ({:validate => false})
      
      ActiveRecord::StatementInvalid:
        Could not find table 'minter_states'
      # ./spec/models/object_resource_spec.rb:77:in `block (3 levels) in <top (required)>'

Finished in 17.86 seconds (files took 7.62 seconds to load)
124 examples, 88 failures, 5 pending

**Comment by lsitu** [comment]
@VivianChu Ah, yes, please run `RAILS_ENV=test rake db:migrate` for test environment.

**Comment by VivianChu** [comment]
@lsitu - I got this error /Users/tchu/Downloads/work/horton2/horton/db/migrate/20170110223602_create_searches.blacklight.rb:5:in `up'
SQLite3::SQLException: table "searches" already exists
/Users/tchu/Downloads/work/horton2/horton/db/migrate/20170110223602_create_searches.blacklight.rb:5:in `up'
Tasks: TOP => db:migrate

**Comment by lsitu** [comment]
@VivianChu It looks like it's conflicting with the local database. Run `rake db:drop` and then `rake db:migrate` should fix it. Thanks for bringing it up.

**Comment by VivianChu** [comment]
@lsitu - I got errors with db:drop, and db:migrate, etc...  However, I did another clone and the tests passed.  Thanks

**Comment by lsitu** [comment]
Thanks @VivianChu for trying it out.

**Comment by lsitu** [comment]
@VivianChu I just corrected the class name change in Hyrax for MemberSearchBuilder, which is Hyrax::MemberWithFilesSearchBuilder now. Please check out the branch again. Thanks.

**Comment by VivianChu** [comment]
@lsitu - I checked out the branch again and the tests passed.

**Comment by lsitu** [comment]
Thanks @VivianChu.

**Pull request merged**
