### PR TITLE
Feature/hyrax upgrade

### LINKED ISSUE #135: Upgrade to latest hyrax
### Descriptive summary

- Please update to the latest Hyrax commit.
- Please provide a summary of the changes in the PR so the entire team understands the context of the changes.

Hyrax 2 beta1 - https://github.com/samvera/hyrax/releases/tag/v2.0.0.beta1

### Rationale

Keeping up to date with Hyrax upstream development. Be prepared well for the upcoming 2.0 version release.

### PR DESCRIPTION
**Pull request by VivianChu**
Fixes #135  ; refs #135 

Upgrade to Hyrax 2 beta1.

Changes proposed in this pull request:
* Gemfile
* Change collection path into dashboard collection path
* Move collection forms into dashboard/collection
* Update work form
* Override dashboard collection controller and hyrax permission_badges using Module#prepend
* Collection_spec tests.

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by mcritchlow** [comment]
@lsitu or @hweng could you take a look at this please?

**Comment by lsitu** [comment]
It looks good. 👍 
@mcritchlow It looks like we may need to set up another upgrade ticket since this 2.0.0.beta1  upgrade is a month from now already.

**Review by mcritchlow — APPROVED** [review]
LGTM, noting that we need to keep an eye on the upstream bug filed by @VivianChu

**Comment by mcritchlow** [comment]
@lsitu - Yep good call, have that setup in #143

**Pull request merged**
