### PR TITLE
Fixes using Questioning Authority gem for local authority CVs support. #46

### PR DESCRIPTION
**Pull request by lsitu**
https://github.com/ucsdlib/dams5-cc-pilot/issues/46

### CODE REVIEW

**Comment by lsitu** [comment]
@ucsdlib/developers Please review, comments ... Thanks.

**Comment by hweng** [comment]
:+1:

**Comment by VivianChu** [comment]
👍

**Comment by lsitu** [comment]
Thank you all for the review and merging.

**Pull request merged**
