### PR TITLE
Fixes #57 -Integrated advanced search

### LINKED ISSUE #57: Port Advanced Search
### Descriptive summary

damspas currently uses an older version of the Blacklight Advanced Search plugin [1].

Please add the latest version of this plugin to Horton and mirror the configuration from damspas as much as it is practical. Please comment if configuration issues arise we should discuss, but the idea is for an "out of the box" evaluation of the latest plugin prior to any significant configuration changes.

1. https://github.com/projectblacklight/blacklight_advanced_search  

### Rationale

In order for stakeholders to evaluate whether the newer plugin will satisfy the advanced search needs for DAMS5, we need to install the latest plugin in Horton.

### PR DESCRIPTION
**Pull request by hweng**
Fixes #57 ; refs #57

@ucsdlib/developers - please review

### CODE REVIEW

**Review by mcritchlow — CHANGES_REQUESTED** [review]
👍 

Looks like we may need to add `coverage/*` to the gitignore.

**Comment by hweng** [comment]
@mcritchlow The coverage/  has been added to the gitignore.

**Comment by mcritchlow** [comment]
The 3 coverage files still appear to be listed in the PR, so the commit may need to be amended to remove them?

**Comment by hweng** [comment]
@mcritchlow The coverage files are removed.

**Review by mcritchlow — APPROVED** [review]

**Comment by lsitu** [comment]
👍

**Pull request merged**
