### PR TITLE
Fixes #67 - Implemented blank node with edit form support for related resource.

### LINKED ISSUE #67: R&D RelatedResource implementation
### Descriptive summary

After a discussion with @ucsdlib/domm we agreed to do a bit more thinking about the best way to model the relatedResource class and related predicates that will use the class.

After speaking with @lsitu we agreed that it would be best to do some R&D, from a technical standpoint, to help make a decision about the following options:

1. Create individual relatedResource predicates for each "type". The class itself only has a label and (optional) URL properties
2. Create a single relatedResource predicate. The class contains a label, (optional) URL, and a type property that pulls from a CV list.

### Rationale

Knowing how the Hyrax framework best handles this kind of modeling choice, from both a form and end-user display standpoint, will hopefully help us decide how to complete this mapping.

### PR DESCRIPTION
**Pull request by lsitu**
Fixes #67; refs #67

Implemented blank node support with edit form for related resource.

Changes proposed in this pull request:
* Added the Intangible model for related resources.
* Implemented nested resource support for object and collection. 
* Added blank node support to the edit form form.
* Refactored the codes for TimeSpan as general support.
* Added more tests to improve test coverage.

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by lsitu** [comment]
@ucsdlib/developers Please review, comments ... Thanks.

**Comment by VivianChu** [comment]
👍

**Comment by hweng** [comment]
:+1:

**Review by mcritchlow — APPROVED** [review]

**Comment by lsitu** [comment]
Thanks Matt and Thank you all for the review.

**Pull request merged**
