### PR TITLE
Upgraded hyrax to include the commit that corrected the FlipFlop typo.

### LINKED ISSUE #110: Upgrade Hyrax dependencies
### Descriptive summary

- [x] Update to latest Hyrax 2.0-alpha commit
- [x] Gemnasium: https://gemnasium.com/github.com/ucsdlib/horton/alerts

### Rationale

Addressing vulnerabilities in dependencies, stay up to date with Hyrax changes.

### PR DESCRIPTION
**Pull request by lsitu**
Upgraded hyrax to include the commit that fixed the FlipFlop typo.

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by hweng** [comment]
@lsitu Looks good. But the ticket requires to update to latest commit. And your upgrades check out the commit 22 days ago: https://github.com/samvera-labs/hyrax/commit/6688333c9343fd7d2e19594661522a826d871951

There are new updates or fixes added to hydra master branch in the past 22 days,  our local development might be conflict with it.  It's better to stay up to date with Hyrax development. Could you update to the latest or more recently one?

**Comment by mcritchlow** [comment]
@hweng - In our planning meeting yesterday, we agreed that @lsitu would update to this commit in order to rebase and merge #108 , and then in a separate commit/PR he would update to the most recent commit possible.

It is true that this won't fix #110 as described, so perhaps we could remove that from the commit message/PR title?

**Comment by hweng** [comment]
@mcritchlow Yup, sounds good to me.

**Comment by lsitu** [comment]
@mcritchlow @hweng Done to remove #110 reference.

**Review by hweng — APPROVED** [review]
:+1:

**Comment by mcritchlow** [comment]
Assuming Circle-CI is happy, LGTM 👍

**Pull request merged**
