### PR TITLE
Close #64 - Update README to add instruction for creating an administrative set.

### LINKED ISSUE #64: Upgrade to latest Hyrax
### Descriptive summary

Many commits have been introduced in Hyrax over the last few weeks.

Please:

- update our application to point to the latest.
- Confirm all tests still pass
- If any errors arise that seem to be upstream issues with Hyrax, please reach out and create issues in the Hyrax repository as needed.

### Rationale

In order to not fall significantly behind on the pace of change with Hyrax, we need to be vigilant about keeping up-to-date with the latest changes.

### PR DESCRIPTION
**Pull request by lsitu**
Fixes #64

Update README to add instruction for creating an administrative set.

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by VivianChu** [comment]
@lsitu - I'm wondering if we need to run this command command rake add_admin_role first before creating an administrative set.

**Comment by lsitu** [comment]
@VivianChu Yes, we have to and its there on README (https://github.com/ucsdlib/horton/blob/develop/README.md#adding-an-admin-role-to-the-last-user) already.

**Comment by VivianChu** [comment]
👍

**Comment by hweng** [comment]
:+1:

**Review by VivianChu — APPROVED** [review]

**Pull request merged**
