### PR TITLE
Fixes #2 Add function to display all components in a complex object.

### LINKED ISSUE #2: R&D porting existing pilot codes for displaying components in a complex object
This will include the following R&D works done in dams5-cc-pilot:
https://github.com/ucsdlib/dams5-cc-pilot/issues/6
https://github.com/ucsdlib/dams5-cc-pilot/issues/28

### PR DESCRIPTION
**Pull request by VivianChu**

### CODE REVIEW

**Comment by VivianChu** [comment]
@ucsdlib/developers  - Please review, comment, etc.... Thanks

**Comment by lsitu** [comment]
@VivianChu It looks good 👍 . But it look like it is conflicting with PR https://github.com/ucsdlib/horton/pull/7 for the object_resource factory class. We'll see how to fix the conflicting codes and merge it.

**Comment by VivianChu** [comment]
@lsitu - I can wait until your PR is merged and I will fix the conflict.

**Comment by lsitu** [comment]
@VivianChu Thanks. It could be just setting the default visibility in the class and appending other codes.

**Comment by VivianChu** [comment]
@lsitu @hweng - The merge conflicts have been merged.  Could you review the changes?  Thanks

**Comment by lsitu** [comment]
👍

**Comment by VivianChu** [comment]
Thanks everyone for reviewing and @hweng for merging.

**Pull request merged**
