### PR TITLE
Fixes configuring Sidekiq as a queue option. #17

### PR DESCRIPTION
**Pull request by lsitu**
https://github.com/ucsdlib/horton/issues/17sidekiq 
Start Sidekiq in a separate tab/window with:
`bundle install`
`bundle exec sidekiq`

### CODE REVIEW

**Comment by VivianChu** [comment]
👍

**Comment by lsitu** [comment]
@ucsdlib/developers I've rebased the PR and it's ready for review now. Thanks.

**Comment by mcritchlow** [comment]
@lsitu - would you mind adding a note in the README on how to start Sidekiq, similar to your initial [comment in this PR](https://github.com/ucsdlib/horton/pull/26#issue-201678138)

**Comment by lsitu** [comment]
@mcritchlow I've updated README to add a note for starting Sidekiq in my last commit https://github.com/ucsdlib/horton/pull/26/commits/b4b9d8716bf475f6362056167494a33da33a7639.

**Pull request merged**
